export interface Company {
    id?: string,
    公司名?: string,
    曾用名?: string,
    公司简介?: string,
    电话?: string,
    官网?: string,
    邮箱?: string,
    地址?: string,
    在业状态?: string,
    ceo?: string,
    注册资本?: string,
    实缴资本?: string,
    经营状态?: string,
    成立日期?: string,
    统一社会信用代码?: string,
    纳税人识别号?: string,
    注册号?: string,
    组织机构代码?: string,
    公司类型?: string,
    所属行业?: string,
    核准日期?: string,
    登记机关?: string,
    所属地区?: string,
    英文名?: string,
    参保人数?: string,
    人员规模?: string,
    营业期限?: string,
    企业地址?: string,
    经营范围?: string,
    投资总数?: string,
    last_update_time?: string; // 最后一次更新时间
}
